# Generated by Django 5.2.5 on 2026-03-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_country",
            field=models.CharField(
                default="Ukraine", max_length=100, verbose_name="Країна доставки"
            ),
            preserve_default=False,
        ),
    ]
